### ISSUE TITLE
Maze files hierarchy

### ISSUE THREAD

**Issue by Peque** [micromouseonline/mazefiles#1]
First of all, thanks for creating this repository, I am already using your maze files in my, for now very basic, maze search algorithm simulator (source code is available, but I am still documenting it...):

https://www.youtube.com/watch?v=6Om6xij6LAw

I just wanted to share my thoughts on this repository hierarchy. I think it would make sense to have a folder to store all the maze files (so that they are separated from the README file and, perhaps, the LICENSE file if you add one). This way you could add continuous integration files too (i.e.: Travis, test scripts), without mixing them with the actual maze files. I could help with CI if you want to add that to this repo.

Example:

```
/
    16x16/
        japan2017.txt
        ...
    32x32/
        japan2017.txt
    README.rst
    LICENSE
    .travis.yml
```

As you see, I think this repository could contain not only classic maze files but maybe also half-size maze files too. The definitive, universal micromouse maze files collection everybody uses and contributes to. :joy:

Feel free to ignore this and close this issue if you do not agree. If that is the case I will not bother you again with this! :blush:

**Comment by micromouseonline** [comment]
Yes.


As soon as I uploaded, it was clear that is would have to be organised better.

In keeping with the Japanese contest classification, I think a better directory structure would be:

├── classic
├── halfsize



The classic mazes are all 16x16 and the halfsize are all 32x32 - even if all the cells are not used.

(I need to update my maze editor to allow it to manage half-size mazes)

The text maze format would allow a description after the maze data if it is always assumed that the maze was square and of the implied size. I have often thought it would be good to have additional text. It could describe the maze/contest and possibly have things like the best run time and the contest leaderboard.

Probably, that would need some kind of format to be specified. Or it could simply be comments in freeform text.

I know nothing of significance about CI. Perhaps you could enlighten me on the possibilities here?

Peter Harrison
peter.harrison@helicron.net

**Comment by micromouseonline** [comment]
I have also added a training folder for potentially non-legal mazes used only for test/training.

Peter Harrison
peter.harrison@helicron.net

**Comment by Peque** [comment]
Great news! :blush:

Actually, I like your "classic/halfsize" folder naming better.

About CI, I can add a script to check valid maze file formatting and compliance that we can integrate with Travis so that any pull-request is automatically checked for errors (it will make reviewing easier). It would also allow any potential contributor to receive feedback almost instantly, without needing to tell them what they did wrong (Travis will take care of that).

I will work on it and open a pull-request with the script and necessary CI configuration once I have it. Should not take too long. :+1:
