### ISSUE TITLE
Travis may be misconfigured

### ISSUE THREAD

**Issue by Peque** [micromouseonline/mazefiles#13]
It seems pipelines stopped being triggered after 5cf70cefcca4c81400899ce40b807016004a9553.

**Comment by micromouseonline** [comment]
I just did some commits - with and without travis checking failures and it all seemed to go through OK

**Comment by Peque** [comment]
Yeah, looks good now. I don't know why pipelines didn't trigger with https://github.com/micromouseonline/mazefiles/pull/14. :woman_shrugging:

**Comment by Peque** [comment]
So it seems pipelines for #15 are not triggered (?).

Could it be that Travis is misconfigured for pull-requests? There is an option that should be active in your project's Travis configuration:

![Screenshot from 2019-04-30 19-16-40](https://user-images.githubusercontent.com/526577/56980404-8c91e880-6b7c-11e9-986f-3472fa653ef2.png)

**Comment by micromouseonline** [comment]
I have no idea where to go to look for that. The whole Travis thing is a mystery to me. (mostly, what is in it for them?)

**Comment by Peque** [comment]
@micromouseonline I would guess it is https://travis-ci.org/micromouseonline/mazefiles/settings

**Comment by micromouseonline** [comment]
Looks the same to me:

![image](https://user-images.githubusercontent.com/667050/57008786-7458b280-6bea-11e9-9b4b-da09859bd224.png)

**Comment by Peque** [comment]
I will close this again then. Do not know why pipelines did not trigger. :woman_shrugging:
