### ISSUE TITLE
UK Spring 2023 half-size map has the goal in the wrong place

### ISSUE THREAD

**Issue by StuartLivings** [micromouseonline/mazefiles#19]
The goal for the half-size map "uk-spring-2023-half-size.txt" is one cell too far North.

**Comment by micromouseonline** [comment]
Do you have a photo of the maze to correct against?

**Comment by StuartLivings** [comment]
I created this issue as a shell to create a PR against, then realised retrospectively that I don't have permissions to create a PR.  If you're willing to grant branch push I have a PR to fix the following:

### Goal position for uk-spring-2023-half-size and ph-001
The text file for uk-spring-2023-half-size has the goal in the top row and second row, but the walls in the text file show the goal in the second row and third row.

The same is also true for ph-001.txt, which has the goal one row too far south (in the centre of the maze), where the walls indicate that the true goal is one row north of the centre of the maze.

### Case sensitivity issue for all-mazes filename test
On Windows python is case insensitive but preserves case.  This causes the regex in test_mazes.py line 60 to fail on all mazes with capitalised filenames.

### Halfsize maze in the wrong directory
classic/uk2021-haz-half.txt fails the pytest because the maze is 32c x 32c.  Moving this maze to the halfsize directory resolves this problem because halfsize mazes aren't currently checked for size.

ph-001.txt also moves from classic to halfsize, as the goal isn't in the centre of the maze.

### Add wall location checking for goal areas
test_mazes.py now checks that the goal rectangle does not contain any interior walls.

I'm happy to provide the diffs for my changes if you prefer, but if you're willing to grant branch push I'll push up my branch and create a PR for you to browse (and criticise!) the proposed changes.

**Comment by micromouseonline** [comment]
Thank you for taking the time to look at this and check stuff.

If you create your own fork of the repository, would that not let you create pull requests?
https://docs.github.com/en/get-started/exploring-projects-on-github/contributing-to-a-project

It would also be best to separate out the issues into chunks. So, errors in a maze file would be one thing, changes to the script would be another.

There are, no doubt, errors in some of the maze files. They come from many sources. Where possible though I would want some corroborating evidence for change in contest mazes if you have it.
 
Case insensitive Windows filenames are a constant source of annoyance.

**Comment by StuartLivings** [comment]
#20 created for all changes, individual changes listed as separate commits in case you wish to cherry-pick some and not others.
