### ISSUE TITLE
Simplify classic file names

### ISSUE THREAD

**Issue by Peque** [micromouseonline/mazefiles#5]
Do you think it would make sense to remove all `-classic-16x16` from the `classic/` maze files? It is kind of redundant information and would make names a bit shorter.

Also, would not it be better to remove the "counter" in some files (i.e.: the recently added NTF files)? It does not seem to be meaningful and there is already the year number which would maintain the same sorting.

I can do it if you want me to, but I thought I would ask first, just in case you did not want to change it... :blush:

**Comment by micromouseonline** [comment]
The “-16x16” is redundant.
The “-classic” probably is as well.

Take care to preserve the other qualifiers though.

The counter is useful as a double check with potential other sources. The all Japan contest, for example, is sometimes referred to as the 23rd or 32nd and so on. I would like that to remain for now.

There are other conflicts to be resolved by inspection as well. For example, my japan2009ef vs the NTF alljapan-030-2009. They differ by one wall. I need to look out a photo and see which is correct.

Ah - https://i.ytimg.com/vi/thFB5Aok_Gw/hqdefault.jpg

Looks like mine is right and theirs is wrong. That puts the cat among the pigeons. I will make the correction and push it up now.

Done

We need a tool that will count the number of wall differences between all the mazes. Even though that is over 200,000 results. There are probably several other examples where there is only one wall difference.

Peter Harrison
peter.harrison@helicron.net

**Comment by micromouseonline** [comment]
Just found these as well:

http://www.tcp4me.com/mmr/mazes/


Peter Harrison
peter.harrison@helicron.net

**Comment by Peque** [comment]
Okay, it makes sense to keep the counter in that case.

Try this for comparing:

```python
from itertools import combinations
from pathlib import Path

from mmsim.mazes import load_maze


# Load mazes
data = {}
for maze in Path('classic').glob('*.txt'):
    data[maze.name] = load_maze(maze)

# Compare mazes
for (a_name, a_data), (b_name, b_data) in combinations(data.items(), 2):
    diff = abs(a_data - b_data).astype(bool).sum()
    if diff <= 2:
        print('%d:\n  %s\n  %s' % (diff, a_name, b_name))
```

Note I use `diff <= 2` because that representation has 4 walls per cell, which means one wall difference may result in two cells having different numbers.

**Comment by micromouseonline** [comment]
Have you run that on a local copy? What did you get?

Peter Harrison
peter.harrison@helicron.net

**Comment by Peque** [comment]
Sure. Sorted by differences, starting from 0 and until 4:

![screenshot from 2018-03-27 01-07-34](https://user-images.githubusercontent.com/526577/37937787-672f156a-315b-11e8-9f45-d7f66494ea1c.png)
![screenshot from 2018-03-27 01-07-54](https://user-images.githubusercontent.com/526577/37937788-674efd6c-315b-11e8-8e3d-dc0278e72cbd.png)
![screenshot from 2018-03-27 01-08-19](https://user-images.githubusercontent.com/526577/37937789-676d37e6-315b-11e8-9df9-1f71eb459a2f.png)
![screenshot from 2018-03-27 01-08-31](https://user-images.githubusercontent.com/526577/37937790-678c34f2-315b-11e8-9008-d0c584e3ce2a.png)

**Comment by micromouseonline** [comment]
For some reason, I seem to have a bunch of files that re exactly 10 years out from the NTF record.

**Comment by micromouseonline** [comment]
UK maze design if often very lazy with slightly modified older mazes being used.

**Comment by micromouseonline** [comment]
And UK finals are frequently minor modifications to the qualifier maze.

**Comment by micromouseonline** [comment]
Unless you spot any others that are clearly close duplicates, I think I will leave them alone. 

There is little or no evidence about which are correct. Or even that either are correct.

For example, japan10 and alljapan-010-…

They differ by one wall but the NTF variant is legal and yet is seems like an unlikely contest maze because of the enclosed area top right. japan10.txt is simply illegal so I will remove it.

**Comment by Peque** [comment]
Closing in favor of #6.
